name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.compiler }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [clang, gcc]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: make
      run: |
        make
